### ISSUE TITLE
Parent and Child same field

### ISSUE THREAD

**Issue by venjirai** [GuidoPreite/DOSM#15]
Just a thought, would it be possible to allow to select parent and child to be the same field?
This could be used as a "Status transition rules" replacement that only work in forms but can be used with every option set.
Let's say we have a "number" field with following options:
- 1
- 2
- 3
and it should only be possible to go from 1 to 2 and from 2 to 3 and in reverse.
It should not be possible to go from 1 directly to 3.

With your solution I would then set the "number" field to be both the parent and child and then I would set up the items like this:
1: 1,2
2: 1,2,3
3: 2,3

**Comment by GuidoPreite** [comment]
Hi @venjirai , this is not possible also with changes to the current library. The purpose of the library is to create a dependency on two fields, not to act on a single field.
As I understood from your description you would like to limit the movements inside the same optionset, I honestly don''t know if it can be done with a single optionset on a form, probably will require another field just to store the previous value to verify if the movement condition is allowed or not. Also for this I suggest you to write some custom javascript because it will probably need the extra field as I wrote before.
